### ISSUE TITLE
Termine aus dem vergangenen Semester erhalten?

### ISSUE THREAD

**Issue by stroebjo** [HAWHHCalendarBot/Backend#8]
Sobald die neuen Terminpläne verfügbar sind, zieht der Bot sich die neuen Termine und man hat die gleichen Veranstaltungen im neuen Semester schon subscribed. Allerdings verschwinden dann die Termine aus dem alten Semester (bei der Google Calendar Import Variante). 

Wäre es möglich nach dem Semesterende alle existierenden Termine dauerhaft zu kopieren in die Import Datei? Oder vllt einfach eine Pushnotifcation das man sich die Datei selber noch einmal sichern kann?

**Comment by EdJoPaTo** [comment]
@stroebjo Wenn ich das richtig sehe, wäre es wohl das einfachste für dich, dir selbst eine Erinnerung zum Beispiel nach den Klausuren zu machen. Dann kannst du das aktuelle importieren und direkt eine Erinnerung fürs nächste Semester erstellen.

Hilft dir das schon?

**Comment by stroebjo** [comment]
Ja, klar! Ich hatte nur ursprünglich nicht darüber nachgedacht, dass der Bot im neuen Semester die Termine neu crawled und dem entsprechend natürlich die alten wegwirft. Ist aber logisch. ;)
